// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Output } from "./Output";

export interface BaseOutput { id: string, output: Output, }