// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputConfiguration } from "./OutputConfiguration";

export interface BaseOutputConfiguration { id: string, output: OutputConfiguration, }