// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DmxControllerConfiguration } from "./DmxControllerConfiguration";
import type { DmxControllerData } from "./DmxControllerData";

export type DmxControllerMessage = { "type": "UpdateConfiguration" } & DmxControllerConfiguration | { "type": "Data" } & DmxControllerData;