// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DmxOutput } from "./DmxOutput";
import type { WledOutput } from "./WledOutput";

export type Output = { type: "Dmx" } & DmxOutput | { type: "Wled" } & WledOutput;