// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WsMessage } from "./WsMessage";

export type RenderedFile = { audio: Int8Array, timestamps: Array<number>, controllers: Array<WsMessage>, commands: Array<Array<WsMessage>>, };