// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControllerType } from "./ControllerType";

export type WsMessage = { "type": "AddController", id: string, controller_type: ControllerType, } | { "type": "RemoveController", id: string, } | { "type": "CallController", id: string, message: string, };