name: Deploy to Pages

on:
    push:
        branches: ["main"]
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

# Allow one concurrent deployment
concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Node
              uses: actions/setup-node@v3
              with:
                  node-version: 21
                  cache: "yarn"
            - name: Setup Yarn v3
              run: |
                  corepack enable
                  corepack prepare yarn@stable --activate
            - name: Install dependencies
              run: yarn install
            - name: Build
              run: yarn run build
              env:
                  BASE_URL: "/ledmusicstudio/"
            - name: Setup Pages
              uses: actions/configure-pages@v3
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v2
              with:
                  path: "./dist"
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v2
